-- Aula 03/04/2020
-- SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY, DISTINCT, TOP.
-- OPERADORES OR, AND E NOT
-- CARACTERE (SOMENTE STRING) CORINGA --> LIKE --> %, __ , []
-- OPERADORES PREDICATOS -> IN, BETWEEN
-- VALORES NULOS --> IS NULL, IS NOT NULL.
-- AS -> ALIAS (RENOMEIA O NOME DA COLUNA NO SELECT)

USE PEDIDOS;

SELECT * FROM TB_CARGO